# Generated by Django 5.2.11 on 2026-02-16 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=200, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='orders.order')),
            ],
        ),
    ]
