# Generated by Django 5.2.11 on 2026-02-17 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_payment_fields'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='zarinpal', max_length=50)),
                ('stage', models.CharField(choices=[('REQUEST', 'Request'), ('VERIFY', 'Verify')], max_length=10)),
                ('authority', models.CharField(blank=True, max_length=255)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('ref_id', models.BigIntegerField(blank=True, null=True)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='orders.order')),
            ],
        ),
    ]
